/* Supplemental final-exam question banks, keyed by track id. Exams draw
   randomly from these plus the track's module quiz questions. */
import type { Question } from "./types";

export const EXAM_BANK: Record<string, Question[]> = {
  net: [
    {
      q: "A host at 172.16.44.200/21 needs to reach 172.16.40.9. What does it do first?",
      opts: [
        "Sends the packet to its default gateway — .44.x and .40.x are different /24s",
        "Broadcasts the packet to 172.16.47.255 and lets the target pick it up",
        "ARPs for 172.16.40.9 directly — both addresses sit inside 172.16.40.0/21",
        "ARPs for the gateway's MAC, then addresses the frame to 172.16.40.9",
      ],
      a: 2,
      why: "A /21 masks all but 3 bits of the third octet — block size 8 — so 172.16.40.0/21 spans **.40.0 through .47.255**, and both hosts are local: ARP directly. The gateway answer is the classic trap of reading subnets at octet boundaries instead of applying the mask.",
    },
    {
      q: "You must carve 192.168.80.0/24 into at least 6 subnets, each holding at least 25 hosts. Which mask works?",
      opts: [
        "255.255.255.192 (/26)",
        "255.255.255.224 (/27)",
        "255.255.255.240 (/28)",
        "255.255.255.128 (/25)",
      ],
      a: 1,
      why: "A /27 yields **8 subnets of 30 usable hosts** — both constraints met. /26 gives 62 hosts but only 4 subnets; /28 gives 16 subnets but only 14 hosts each.",
    },
    {
      q: "What is the broadcast address for the subnet containing 10.33.71.22/19?",
      opts: ["10.33.71.255", "10.33.79.255", "10.33.95.255", "10.33.127.255"],
      a: 2,
      why: "A /19 has block size 32 in the third octet: 10.33.71.22 falls in **10.33.64.0–10.33.95.255**, so the broadcast is 10.33.95.255. 10.33.79.255 is the /20 answer — one bit too many.",
    },
    {
      q: "A TCP receiver advertises a fixed 128 KB window. The path RTT is 80 ms with zero loss. What throughput ceiling does the window impose?",
      opts: [
        "~13 Mbps",
        "~1.6 Mbps",
        "~131 Mbps",
        "None — without loss, throughput is limited only by link speed",
      ],
      a: 0,
      why: "One window per RTT: 131072 bytes / 0.08 s = 1.64 MB/s ≈ **13.1 Mbps**. The ~1.6 answer forgets to convert bytes to bits; and the window absolutely caps throughput even on a clean path — that's the long-fat-network problem.",
    },
    {
      q: "A segment arrives carrying sequence number 1000 with 400 bytes of payload. What ACK number does the receiver send?",
      opts: ["1000", "1400", "1401", "1399"],
      a: 1,
      why: "ACK numbers are **cumulative and name the next byte expected**: bytes 1000–1399 arrived, so the receiver asks for 1400. 1401 is off-by-one — the ACK isn't 'last byte + 1 + 1', and only SYN/FIN consume a sequence number without carrying data.",
    },
    {
      q: "Your WireGuard tunnel rides a PPPoE uplink (MTU 1492), and WireGuard adds 60 bytes of overhead. What is the largest safe TCP MSS for IPv4 connections inside the tunnel?",
      opts: ["1460", "1452", "1432", "1392"],
      a: 3,
      why: "Tunnel MTU is 1492 − 60 = **1432**; subtract the inner 20-byte IP and 20-byte TCP headers to get MSS 1392. 1432 is the tempting miss — that's the tunnel MTU itself, not the payload an MSS describes.",
    },
    {
      q: "Your server accumulates hundreds of connections stuck in CLOSE_WAIT that never clear. The verdict?",
      opts: [
        "Normal TIME_WAIT behavior; the kernel clears them after 2×MSL",
        "The network is dropping your FINs, so the close handshake never completes",
        "Your application received the peers' FINs but never calls close() — a local code bug",
        "TCP keepalive is disabled, so dead peers are never detected",
      ],
      a: 2,
      why: "CLOSE_WAIT means the kernel ACKed the peer's FIN and is **waiting for your application to close the socket** — it persists until your code acts. TIME_WAIT is the state that clears itself; CLOSE_WAIT piling up is always an application-side leak.",
    },
    {
      q: "An edge router advertises the summary 172.20.0.0/22 upstream, but only 172.20.0.0/24 and 172.20.1.0/24 exist internally, and the edge's own default route points back upstream. A packet arrives for 172.20.3.9. What prevents it from looping?",
      opts: [
        "Nothing needs to — the packet loops until TTL expires, which is acceptable",
        "A discard (null) route for 172.20.0.0/22 on the summarizing router",
        "Split horizon stops the upstream from sending it back",
        "An ICMP redirect teaches the upstream that the subnet doesn't exist",
      ],
      a: 1,
      why: "The summarizing router installs a **null/discard route for the aggregate**: destinations inside the summary with no longer match are dropped (with ICMP unreachable) instead of following the default back upstream. TTL expiry does 'work' — after burning bandwidth on up to 60+ round trips per packet, which is exactly the loop you must design out.",
    },
    {
      q: "Your router knows 10.0.0.0/8 as a static route (AD 1) and 10.7.0.0/16 via OSPF (AD 110). Which one forwards a packet to 10.7.3.9?",
      opts: [
        "The OSPF route — prefix length is compared before administrative distance",
        "The static route — AD 1 beats AD 110",
        "Both are installed for that host and traffic load-balances",
        "The static route, because static routes always win regardless of metrics",
      ],
      a: 0,
      why: "**Longest prefix match is the first tiebreak** at forwarding time: /16 beats /8, full stop. Administrative distance only arbitrates between routes to the *same* prefix learned from different sources — the common exam trap is applying it across different prefixes.",
    },
    {
      q: "Your dual-homed AS wants inbound traffic to prefer ISP-A over ISP-B. Which knob actually influences what other networks choose?",
      opts: [
        "Raise local-preference on routes learned from ISP-A",
        "Lower your IGP metric toward ISP-A",
        "Set a higher weight on the ISP-A BGP session",
        "Prepend your own AS several times on advertisements sent to ISP-B",
      ],
      a: 3,
      why: "Inbound path choice is made by **other networks**, so you must make your prefix look worse via ISP-B — AS-path prepending is the standard lever. Local-preference (and weight) shape your *outbound* decisions only; that's the strongest distractor because it's the right tool for the opposite direction.",
    },
    {
      q: "A port-forward to an internal server works perfectly from the internet, but LAN clients connecting to the server's public IP time out. Why?",
      opts: [
        "The router doesn't hairpin — it won't apply the port-forward (and re-NAT the source) for packets arriving on its LAN interface",
        "The server rejects connections from RFC 1918 source addresses",
        "The port-forward only supports one concurrent client",
        "The client's ARP cache maps the public IP to the wrong MAC",
      ],
      a: 0,
      why: "This is missing **hairpin (NAT loopback)**: LAN-to-public-IP traffic needs both the DNAT and a source rewrite so replies return via the router, and many gateways simply don't do it. The clean fix is split-horizon DNS handing LAN clients the private address; nothing about the server itself is filtering RFC 1918.",
    },
    {
      q: "Your ISP uses CGNAT. You set up a port-forward on your home router for a game server, but nobody outside can connect. The reason?",
      opts: [
        "You forwarded UDP but the game uses TCP",
        "The router's firewall overrides its own port-forward rules",
        "Your router's WAN address is itself private (100.64.0.0/10) — the carrier's NAT has no forwarding entry for you",
        "CGNAT blocks inbound TCP by policy but permits UDP",
      ],
      a: 2,
      why: "Under CGNAT your 'public' side is **shared-address space (100.64/10)** behind the carrier's NAT, which you don't control — your router's forward only handles the inner hop. That's why CGNAT users need outbound-only designs: VPN rendezvous, hole punching, or relays.",
    },
    {
      q: "You publish a brand-new DNS name and it resolves for some users immediately, but users whose resolver was asked for that name minutes *before* you created it keep getting NXDOMAIN. Why?",
      opts: [
        "The record hasn't propagated to all the root servers yet",
        "Their resolvers cached the earlier NXDOMAIN — negative answers are cached per the zone's SOA negative TTL",
        "The new record's own TTL delays visibility of the name",
        "Secondary nameservers only transfer the zone once a day",
      ],
      a: 1,
      why: "**Negative caching (RFC 2308)** stores 'this name does not exist' for the SOA-derived negative TTL, so a pre-creation lookup poisons that resolver until it expires. Roots never hold your records — they only delegate — and the new record's TTL governs how long *positive* answers live, not the old NXDOMAIN.",
    },
    {
      q: "The NS records for example.com point at ns1.example.com — resolving the nameserver's name seems to require the nameserver. Why does this work?",
      opts: [
        "Resolvers special-case in-domain nameservers and skip resolving them",
        "The recursive resolver already knows every nameserver address from its cache",
        "It doesn't — registrars reject this circular configuration",
        "The .com zone serves glue A/AAAA records for ns1.example.com alongside the delegation",
      ],
      a: 3,
      why: "The parent zone breaks the circle with **glue records**: the .com servers return ns1's address in the additional section of the referral. Caching can hide a missing-glue problem for a while, which is exactly why stale glue causes those maddening 'works from here, dead from there' outages.",
    },
    {
      q: "TLS 1.3 0-RTT lets a resuming client send application data with its first flight. Why do careful servers accept only idempotent requests as early data?",
      opts: [
        "Early data is encrypted with a weaker cipher until the handshake completes",
        "Early data isn't authenticated, so it could be forged",
        "An attacker can replay captured early data verbatim, so it must be harmless to execute twice",
        "0-RTT skips certificate validation for speed",
      ],
      a: 2,
      why: "0-RTT data is bound to a previous session's PSK and gets **no fresh anti-replay handshake**, so an on-path attacker can re-send the recorded flight and the server may process it again — fine for `GET`, catastrophic for 'transfer $500'. It's fully encrypted and authenticated under the PSK; replay, not forgery, is the problem.",
    },
    {
      q: "A network silently drops UDP to port 443. What does a modern browser do when loading a site that supports HTTP/3?",
      opts: [
        "Falls back to TCP — TLS with HTTP/2 or 1.1 — when QUIC fails or loses the race",
        "The page fails to load until UDP is allowed",
        "Retries QUIC on UDP port 80",
        "Tunnels QUIC inside a TCP connection to port 443",
      ],
      a: 0,
      why: "Browsers race or fall back: HTTP/3 is discovered via Alt-Svc/HTTPS records but **TCP+TLS remains the safety net**, which is why QUIC blocking degrades performance instead of breaking the web. QUIC is UDP-native — there's no standard QUIC-over-TCP encapsulation to fall back into.",
    },
    {
      q: "Your neighbors' 2.4 GHz APs sit on channels 1, 6, and 11. A new AP appears on channel 3. What does it inflict on channels 1 and 6?",
      opts: [
        "Very little — it uses spectrum the others leave idle",
        "Partial-overlap interference that their carrier sense can't decode and politely defer to — often worse than sharing channel 1 or 6 outright",
        "Co-channel contention with both, halving everyone's airtime fairly",
        "Nothing unless it transmits 40 MHz-wide channels",
      ],
      a: 1,
      why: "On the same channel, CSMA/CA hears other transmissions and **takes turns**; a partially overlapping channel delivers energy the radios can't decode, so it registers as noise and corrupts frames instead of coordinating. That's why 1/6/11 is doctrine — the 'extra spectrum' intuition is exactly backwards.",
    },
    {
      q: "EAP-TLS is cryptographically stronger than PEAP-MSCHAPv2, yet many orgs still deploy PEAP. The dominant operational reason?",
      opts: [
        "EAP-TLS handshakes are too slow for roaming clients",
        "EAP-TLS can't deliver RADIUS attributes for dynamic VLAN assignment",
        "PEAP encrypts the inner exchange; EAP-TLS sends it in the clear",
        "EAP-TLS requires issuing, distributing, and rotating a client certificate for every device — a PKI/MDM investment PEAP sidesteps with passwords",
      ],
      a: 3,
      why: "EAP-TLS's cost is **client-certificate lifecycle**: enrollment, renewal, and revocation across every laptop and phone, which effectively demands MDM/SCEP infrastructure. Both methods run inside a TLS tunnel and both support RADIUS-driven VLANs; the trade is purely provisioning effort versus phishable credentials.",
    },
    {
      q: "A DHCP client unicasts a renewal REQUEST at 50% of its lease (T1) and gets silence. What changes at 87.5% (T2)?",
      opts: [
        "It releases the address and restarts DORA from DISCOVER",
        "It keeps unicasting the same server until the lease expires",
        "It broadcasts its REQUEST so *any* DHCP server can extend the lease",
        "It falls back to a 169.254.x.x address immediately",
      ],
      a: 2,
      why: "At **T2 the client gives up on its original server** and broadcasts, letting a failover partner rebind the lease — this is what makes redundant DHCP work. Only at full expiry does it drop the address and start over; 169.254 link-local is the last resort after DISCOVER also fails.",
    },
    {
      q: "You enabled DHCP snooping, yet clients on the dual-stack LAN are being MITM'd: a rogue device made itself their IPv6 default gateway. How?",
      opts: [
        "DHCP snooping inspects DHCPv4 — rogue Router Advertisements need RA Guard on the switch",
        "The attacker spoofs the legitimate router's MAC, which bypasses snooping",
        "IPv6 traffic can't be MITM'd this way; the cause is elsewhere",
        "DHCP snooping only protects trunk ports, not access ports",
      ],
      a: 0,
      why: "IPv6 hosts learn their gateway from **Router Advertisements, not DHCP**, so a forged RA slides straight past DHCP snooping — the parallel control is RA Guard (plus ND inspection). This is the classic dual-stack blind spot: v4 defenses fully deployed, v6 wide open.",
    },
    {
      q: "tcpdump on your own host shows 'bad checksum' on every single outbound TCP segment, yet all connections work perfectly. Diagnosis?",
      opts: [
        "The NIC is corrupting frames and should be replaced",
        "An MTU mismatch is truncating segments before the checksum",
        "A middlebox is rewriting packets without fixing checksums",
        "Checksum offload — the capture happens before the NIC computes the checksum in hardware",
      ],
      a: 3,
      why: "With TX checksum offload, the kernel hands the NIC a segment with the checksum **left for hardware to fill in**, and tcpdump taps the stack above that point — so locally generated packets look 'broken' while the wire is fine. The tell: it's outbound-only and universal; real corruption would be sporadic and would break connections.",
    },
    {
      q: "Before stateful firewalls, how did a stateless router ACL allow replies to outbound TCP connections without opening the network to inbound connects?",
      opts: [
        "Permit all inbound TCP to ephemeral ports 1024–65535",
        "Permit inbound TCP segments with ACK or RST set — only mid-conversation packets qualify",
        "Permit inbound traffic only from source ports 80 and 443",
        "No rule needed — NAT already blocks unsolicited inbound",
      ],
      a: 1,
      why: "The classic `established` keyword matches **ACK/RST bits**: a connection-opening SYN has neither, so inbound connects die while return traffic flows. Opening all ephemeral ports admits fresh SYNs too — that's the hole this trick exists to avoid — and it's still spoofable, which is why stateful tracking replaced it.",
    },
    {
      q: "A cloud instance in a private subnet must pull OS updates from the internet but never accept inbound connections. The right construct?",
      opts: [
        "Add a 0.0.0.0/0 route to the internet gateway from the private subnet",
        "Attach a public IP to the instance and block inbound with a NACL",
        "Route 0.0.0.0/0 to a NAT gateway that lives in a public subnet",
        "Peer the private subnet with a public VPC",
      ],
      a: 2,
      why: "A **NAT gateway** gives outbound-only reachability: the instance keeps its private address and the internet has nothing to target. Routing straight to the IGW is the tempting miss — an IGW only translates for instances that hold public IPs, so the route alone does nothing (and adding the public IP defeats the design).",
    },
    {
      q: "VPC A is peered with VPC B, and VPC B is peered with VPC C. Can instances in A reach C through B?",
      opts: [
        "No — peering isn't transitive; A needs its own peering to C, or a hub like a transit gateway",
        "Yes, once you add routes for C's CIDR to A's route tables via the A–B peering",
        "Yes — B forwards between its peers automatically",
        "Only if all three CIDRs are non-overlapping",
      ],
      a: 0,
      why: "Cloud peering is strictly **point-to-point**: the fabric drops traffic whose destination isn't in the peered VPC itself, so even hand-added routes to C via the A–B peering go nowhere. That distractor is the trap — route tables can *name* the path, but the peering data plane refuses to carry transit; that's what transit gateways are for.",
    },
  ],

  rust: [
    {
      q: "A task does `let g = state.lock().unwrap();` on a `std::sync::Mutex`, then hits an `.await` before `g` drops. What breaks, and when?",
      opts: [
        "A data race at runtime — two tasks can hold the guard simultaneously",
        "The future becomes !Send, so tokio::spawn rejects it at compile time on the multithreaded runtime",
        "The mutex silently unlocks at the .await and relocks afterward",
        "Nothing — the guard is RAII and behaves identically in async code",
      ],
      a: 1,
      why: "`MutexGuard` is `!Send`, and a future must be `Send` to cross `tokio::spawn` — so the bug is caught **at compile time**, which is the point of the design. There's no silent unlock; and even the `Send`-friendly `tokio::sync::Mutex` held across `.await` invites deadlock and starvation, so the real fix is to scope the lock before awaiting.",
    },
    {
      q: "A method takes `&mut self`, then needs to mutate `self.stats` while iterating `self.peers`. The borrow checker refuses. The idiomatic fix?",
      opts: [
        "Wrap both fields in RefCell and borrow at runtime",
        "Clone the peers list before iterating",
        "Drop to unsafe raw pointers — you know the fields are disjoint",
        "Borrow the fields directly (destructure self) so the compiler sees two disjoint borrows",
      ],
      a: 3,
      why: "The conflict is an artifact of borrowing through `&mut self` as a whole; **split borrows** — `let Self { peers, stats, .. } = self;` or direct field access in one scope — give the compiler exactly the disjointness you already know. `RefCell` trades a compile-time proof for a possible runtime panic, and cloning buys correctness with a per-call allocation you don't need.",
    },
    {
      q: "`let first = &packets[0]; packets.push(extra); send(first);` is rejected. What actual memory hazard is the compiler preventing?",
      opts: [
        "push may reallocate the Vec's buffer, leaving `first` a dangling pointer into freed memory",
        "Vec isn't Sync, so shared and mutable access can never mix",
        "None — it's a borrow-checker limitation, and re-indexing after the push would be equally unsafe",
        "The reference would observe the new element, violating iterator stability",
      ],
      a: 0,
      why: "When capacity runs out, `push` **moves the whole buffer**, so `first` would point into freed memory — a use-after-free in C++, a compile error in Rust. The 'limitation' answer is backwards: re-indexing with `&packets[0]` *after* the push is perfectly safe, which is exactly the escape hatch the rule leaves open.",
    },
    {
      q: "Your function returns `Result<Config, ConfigError>`, but a call inside returns `io::Error` and `?` won't compile. What makes `?` work here?",
      opts: [
        "Annotate the call with .map_err(ConfigError::from) — ? never converts error types",
        "Change the return type to Box<dyn Error>",
        "An impl From<io::Error> for ConfigError (e.g. a #[from] variant with thiserror) — ? inserts the conversion on the error path",
        "Errors must implement Clone for ? to propagate them",
      ],
      a: 2,
      why: "`?` desugars to an early return through `From::from`, so giving `ConfigError` a **`From<io::Error>` impl** (one `#[from]` attribute) makes every call site clean. `map_err` also compiles — but it hand-writes at each call site the conversion `?` was designed to do once, centrally.",
    },
    {
      q: "Your API passes `(String, u16)` host/port pairs everywhere, and a caller swapped two same-typed arguments — it compiled and shipped. The type-driven prevention?",
      opts: [
        "Debug assertions that the strings look like hostnames",
        "type Host = String; and type Port = u16; aliases for readability",
        "Document the argument order and rely on code review",
        "Newtypes — struct Host(String); struct Port(u16); — so swapped arguments become type errors",
      ],
      a: 3,
      why: "**Newtypes** create genuinely distinct types, so the swap can't compile — invalid states become unrepresentable at zero runtime cost. Aliases are the seductive non-fix: `type Host = String` is transparently *the same type*, so the compiler treats them as interchangeable.",
    },
    {
      q: "You `tokio::spawn` a task and immediately drop its JoinHandle. What happens to the task?",
      opts: [
        "It's cancelled immediately, as if aborted",
        "It keeps running detached — dropping the handle only discards your ability to await or abort it",
        "It leaks: the runtime never polls it again",
        "The runtime panics at shutdown if any handle was dropped",
      ],
      a: 1,
      why: "Spawned tasks are owned by the **runtime**, not the handle — dropping the `JoinHandle` just detaches it, unlike scoped/structured APIs where the handle owns the work. Cancellation is explicit (`handle.abort()`); silent detachment is why fire-and-forget spawns need their own error logging.",
    },
    {
      q: "You `.await` 100 independent HTTP fetches inside a for loop and total latency is the sum of all of them. The fix?",
      opts: [
        "Run them concurrently — join_all / FuturesUnordered or spawn each — because a bare .await in a loop fully serializes them",
        "Raise the Tokio worker thread count; the pool is saturated",
        "Switch the runtime to the multi-threaded flavor",
        "Use one std::thread per fetch — async can't parallelize I/O",
      ],
      a: 0,
      why: "A future does nothing until polled, and the loop polls **one at a time to completion** — concurrency must be expressed with `join_all`, `FuturesUnordered`, or spawning. More worker threads is the classic misdiagnosis: the other 99 futures haven't been handed to the runtime at all, so extra threads sit idle.",
    },
    {
      q: "Your hand-written Future returns Poll::Pending but never stores the Waker from the Context. Symptom?",
      opts: [
        "The executor busy-polls it, burning a core until it's ready",
        "A panic — returning Pending without registering a waker violates a checked contract",
        "The task hangs forever — nothing ever signals the executor to poll it again",
        "The runtime falls back to polling it every few milliseconds",
      ],
      a: 2,
      why: "The contract is: return `Pending` **only after arranging for `wake()`** to be called when progress is possible — executors don't re-poll on their own, and nothing checks this at runtime. Busy-polling is what a *bad executor* might do; a correct one simply parks the task, which is why the symptom is a silent, CPU-quiet hang.",
    },
    {
      q: "In poll() you check the ready flag first, and only if it's false do you register the waker. What's wrong?",
      opts: [
        "Nothing — poll holds a lock for its whole duration, so ordering can't matter",
        "The event can fire between the check and the registration — a lost wakeup that hangs the task; register the waker first (or re-check readiness after registering)",
        "The waker may be registered twice, causing a double poll and a panic",
        "Calling wake() on a stale waker aborts the process",
      ],
      a: 1,
      why: "This is the async version of the **lost-wakeup race**: readiness arrives in the gap, `wake()` fires against no registered waker (or the old one), and your `Pending` is never revisited. Duplicate wakes, by contrast, are harmless by design — poll is written to tolerate spurious calls, which is why 'register, then re-check' is the safe pattern.",
    },
    {
      q: "Why must an async fn's future be pinned before it can be polled?",
      opts: [
        "Pin guarantees the future is Send between polls",
        "Pin prevents the future from being dropped while pending",
        "Pin forces the future onto the heap, where addresses are stable",
        "The compiled state machine may hold references into its own state across .await; moving it would invalidate them, so poll requires a promise the memory never moves",
      ],
      a: 3,
      why: "Borrows that live across an `.await` become **self-references inside the state machine**, and moving a self-referential struct leaves pointers into the old location — `Pin` makes 'this won't move' a type-level promise. The heap answer is the common half-truth: `Box::pin` is one way to honor the promise, but `pin!` pins on the stack just fine.",
    },
    {
      q: "A peer sends a 4000-byte UDP datagram and your recv buffer is 1500 bytes. What does your read see?",
      opts: [
        "1500 bytes — the datagram is truncated and the remainder is discarded",
        "1500 bytes now; the next recv returns the remaining 2500",
        "An error, with the datagram left queued intact",
        "The kernel splits it into three buffer-sized reads",
      ],
      a: 0,
      why: "UDP is strictly **one datagram per recv** — whatever doesn't fit is gone (some platforms flag it with `MSG_TRUNC`, none save it for later). The 'next read returns the rest' answer is TCP-stream thinking; datagram boundaries never carry over, which is why tunnel code sizes buffers to max-MTU up front.",
    },
    {
      q: "Your accept loop does `let (stream, _) = listener.accept().await?;` and then handles the connection inline with .await before looping. Symptom under load?",
      opts: [
        "File descriptor exhaustion after ~1024 connections",
        "The listen backlog silently drops SYNs, but connected clients are unaffected",
        "One slow client stalls the loop — no new connection is accepted until its handler finishes; spawn a task per connection instead",
        "Nothing — Tokio runs accepted handlers in parallel automatically",
      ],
      a: 2,
      why: "Handling inline means accept and handler share one task, so a single slow reader **head-of-line blocks every new client** — the canonical fix is `tokio::spawn` per connection. Tokio parallelizes tasks you spawn; it never spawns on your behalf, which is exactly the misconception in the last option.",
    },
    {
      q: "Miri flags your unsafe code for creating a &mut and a & to the same bytes, but every test passes and the release build works. Why is it still a real bug?",
      opts: [
        "UB is a license the optimizer will eventually use — today's passing tests prove nothing about the next compiler version, inlining decision, or call site",
        "It's only undefined on ARM's weaker memory model",
        "It's fine as long as the program stays single-threaded",
        "Miri is over-strict; aliasing a &mut is defined when the reads and writes don't overlap in time",
      ],
      a: 0,
      why: "`&mut` means *unique* — the compiler optimizes on that guarantee (noalias), so violating it is **UB regardless of architecture or thread count**, and miscompilation can appear whenever optimization choices shift. 'Works single-threaded' confuses aliasing UB with data races; they're separate rules and this one needs no second thread.",
    },
    {
      q: "You move an `Rc<RefCell<Config>>` into a tokio::spawn'd task and get a compile error. What exactly is violated?",
      opts: [
        "RefCell isn't Sync, and Sync is what spawn demands",
        "Rc's reference count isn't atomic — moving it to another thread could corrupt the count, so Rc is !Send and the future inherits that",
        "Rc permits cycles, which leak inside async tasks",
        "spawn requires 'static, and Rc borrows from the current thread",
      ],
      a: 1,
      why: "`tokio::spawn` requires the future to be **`Send`**, and `Rc`'s non-atomic refcount makes it `!Send` — the fix is `Arc` (plus `Mutex`/`RwLock` instead of `RefCell`). The `Sync` answer is the tempting near-miss: spawn's bound is `Send` (the value moves), and it's `Rc` that fails it first.",
    },
    {
      q: "Thread A writes a buffer, then stores `ready.store(true, Ordering::Relaxed)`. Thread B loops on `ready.load(Relaxed)`, sees true — and reads stale buffer contents. Why?",
      opts: [
        "Relaxed loads can tear, returning a mix of old and new bits",
        "Only SeqCst is safe for any cross-thread communication",
        "Relaxed is atomic but imposes no ordering — nothing guarantees the buffer writes are visible before the flag; publish with Release and consume with Acquire",
        "B's cache must be flushed manually with a fence on every platform",
      ],
      a: 2,
      why: "`Relaxed` promises atomicity of the flag itself but **no happens-before edge**, so the compiler and CPU may let the flag become visible before the data it 'guards'. A `Release` store paired with an `Acquire` load creates exactly that edge; reaching for `SeqCst` also works but papers over the actual concept being tested.",
    },
    {
      q: "You pass a plain Rust struct by pointer to a C library. It works for months, then a compiler upgrade breaks it. Root cause?",
      opts: [
        "A missing #[no_mangle], so C linked against the wrong symbol",
        "Alignment rules differ between Rust and C only on ARM targets",
        "C code can't legally access memory owned by Rust at all",
        "The default (Rust) layout is unspecified — the compiler may reorder fields and change layout between versions; #[repr(C)] is what pins it",
      ],
      a: 3,
      why: "`repr(Rust)` gives the compiler freedom to **reorder and repack fields**, and nothing obliges two compiler versions to agree — any struct crossing FFI needs `#[repr(C)]`. `#[no_mangle]` is about *function symbol names*, a different FFI requirement entirely; the data layout is what silently shifted here.",
    },
    {
      q: "A C library returns an opaque handle (a raw pointer) that your safe Rust wrapper stores. You want the wrapper to be Send. What does that actually require?",
      opts: [
        "Nothing — raw pointers are already Send, so the wrapper is too",
        "Evidence that the C library permits using the handle from another thread — `unsafe impl Send` is your promise, and the compiler cannot check it",
        "That the struct contains no lifetimes; Send is about lifetimes, not threads",
        "Wrapping it in Mutex, which makes any type Send",
      ],
      a: 1,
      why: "Auto-traits don't propagate through raw pointers (`*mut T` is `!Send`), so you must write **`unsafe impl Send`** — and the `unsafe` marks that its truth rests entirely on the C library's documented threading contract. `Mutex` is the tempting wrap: `Mutex<T>: Send` still requires `T: Send`, so it launders nothing.",
    },
    {
      q: "A stacked-borrows violation in your unsafe parser touches only valid, allocated memory, so nothing crashes. Which tool flags it deterministically when a test exercises the path?",
      opts: [
        "cargo miri — it interprets the code and checks aliasing and validity rules, reporting UB even when no bad address is touched",
        "valgrind — it traps every invalid memory access",
        "cargo clippy with pedantic lints enabled",
        "cargo audit",
      ],
      a: 0,
      why: "Miri executes your program abstractly and enforces **Rust's aliasing model itself**, so UB that corrupts no memory today still gets reported. Valgrind is the strong distractor: it only sees genuinely invalid accesses, and this bug by construction never makes one; clippy doesn't execute code, and audit checks advisories.",
    },
    {
      q: "Your Connection type must send a protocol close frame when it's cleaned up — but that send is async. What's the fundamental problem?",
      opts: [
        "None — implement AsyncDrop, which exists for exactly this",
        "Call block_on inside Drop to run the close future",
        "None — the kernel flushes and closes the socket anyway",
        "Drop is synchronous and cannot await — expose an explicit async close()/shutdown() method, keeping Drop as a best-effort fallback (e.g. spawning the frame)",
      ],
      a: 3,
      why: "There is **no stable AsyncDrop**, so graceful async teardown must be an explicit method callers await — with `Drop` only as a lossy backstop. `block_on` inside `Drop` is the trap: called from runtime context it panics or deadlocks the very executor that's dropping you.",
    },
    {
      q: "Length arithmetic on attacker-controlled packet fields: debug builds panic on overflow, release builds wrap silently. The right production stance?",
      opts: [
        "Rely on release wrapping — it's defined behavior in Rust, unlike C",
        "Cast everything to u64 so overflow can't occur",
        "Use checked_add/checked_sub on untrusted lengths and treat None as a malformed packet",
        "Enable overflow-checks in release and let the panic be the error path",
      ],
      a: 2,
      why: "Wrapping *is* defined — and that's the trap: `defined` isn't `correct`, and a wrapped length becomes a mis-sized buffer operation an attacker steered. **Checked arithmetic** turns the overflow into an explicit protocol error; global release panics convert every hostile packet into a remote crash — a DoS you handed out for free.",
    },
  ],

  tunnel: [
    {
      q: "Reads from your TUN device occasionally return packets that are cut short. Cause?",
      opts: [
        "The kernel splits large packets across consecutive reads; buffer and reassemble them",
        "The remote peer's MTU is larger than yours",
        "Your read buffer is smaller than the interface MTU (plus the packet-info header some platforms prepend) — each read must fit one whole packet",
        "GSO is enabled and must be switched off",
      ],
      a: 2,
      why: "TUN is **packet-per-read**: the kernel hands you exactly one IP packet, and anything beyond your buffer is truncated and lost, never queued for the next read. 'Reassemble across reads' is stream thinking — sizing the buffer to MTU (+4 on utun-style devices) is the whole fix.",
    },
    {
      q: "You open tun0, assign it 10.8.0.2/24, bring it up — and your fd never sees the ping to 8.8.8.8 you ran for testing. Missing piece?",
      opts: [
        "A route — the address only covers 10.8.0.0/24; traffic reaches a TUN device when the routing table sends it there, so 8.8.8.8 needs a default (or covering) route via tun0",
        "Promiscuous mode on tun0",
        "A TAP device — TUN can't receive forwarded traffic",
        "An iptables MASQUERADE rule",
      ],
      a: 0,
      why: "A TUN interface receives exactly what the **routing table** steers into it — assigning an address only installs the connected /24 route. Promiscuous mode is an Ethernet-capture concept; there's no L2 here to sniff.",
    },
    {
      q: "Your single-threaded loop alternates: blocking read on the TUN fd, then a blocking read on the UDP socket. Users report the tunnel freezes when traffic is one-directional. The fix?",
      opts: [
        "Raise the socket receive buffers so reads never block",
        "Set short read timeouts and retry in a loop",
        "Keep blocking reads — the kernel wakes the right one when data arrives",
        "Make both fds nonblocking and multiplex with poll/epoll (or an async runtime) so whichever side is readable gets serviced",
      ],
      a: 3,
      why: "A blocking read on the quiet fd **wedges the whole loop** while the other side has packets waiting — readiness multiplexing (or one task per direction) is the structural answer. Timeouts 'work' by converting the stall into steady added latency and wasted wakeups; they treat the symptom, not the architecture.",
    },
    {
      q: "In an AEAD like ChaCha20-Poly1305, what does the *associated data* (AAD) buy a tunnel protocol?",
      opts: [
        "It encrypts headers that would otherwise leak metadata",
        "Fields the receiver must read before decrypting — receiver index, counter — stay plaintext but are integrity-bound: tamper with them and the tag check fails",
        "It prevents replay of previously captured packets",
        "It strengthens the key by mixing in per-packet data",
      ],
      a: 1,
      why: "AAD is **authenticated, not encrypted** — exactly right for routing/demux fields the receiver needs before it can decrypt anything. It does not stop replay: a re-sent packet is byte-identical, AAD included, and verifies perfectly — that's what counters plus a replay window are for.",
    },
    {
      q: "A packet passes AEAD verification — the tag is valid under the current session key. Why does WireGuard still check its counter against a sliding window before accepting it?",
      opts: [
        "AEAD proves the packet is authentic, not that it's *new* — an attacker can re-send a captured valid packet, so the window rejects duplicate and stale counters",
        "The window repairs packet reordering before handing data to the TUN device",
        "It catches bit-flips the Poly1305 tag might miss",
        "It exists to trigger a rekey when the counter nears exhaustion",
      ],
      a: 0,
      why: "A replayed packet is cryptographically **perfect** — same bytes, same valid tag — so freshness must be enforced separately via the nonce counter and a sliding window. The window tolerates reordering but doesn't repair it; ordering is the inner protocols' problem.",
    },
    {
      q: "WireGuard peers already have each other's static keys — encryption could start immediately. Why does the handshake still perform ephemeral Diffie-Hellman?",
      opts: [
        "Asymmetric crypto is too slow for bulk data, so symmetric session keys must be derived",
        "Static keys are too short to drive an AEAD",
        "Forward secrecy — with ephemeral contributions, a later theft of a static private key cannot decrypt previously recorded traffic",
        "It lets either side rotate static keys without re-pairing",
      ],
      a: 2,
      why: "Ephemeral DH means session keys die with the session: record traffic today, steal the static key next year, and you still get nothing — **forward secrecy**. The speed answer is a true fact aimed at the wrong question: deriving symmetric keys doesn't require *ephemeral* keys; only forward secrecy does.",
    },
    {
      q: "Under handshake flood, a WireGuard responder stops completing handshakes and instead sends cookie replies. What is this buying?",
      opts: [
        "It's the NAT keepalive mechanism engaging under load",
        "DoS defense — the initiator must prove it owns its source IP (a round trip) before the responder spends CPU on the expensive DH computation",
        "It delivers the rotated session key to the peer",
        "It probes path MTU before the tunnel comes up",
      ],
      a: 1,
      why: "Handshake DH math is costly and initiation packets are cheap to spoof; the **cookie round trip forces source-address ownership** and enables per-IP rate limiting before any real work. It carries no keys — just a MAC'd token the initiator must echo in its retried initiation.",
    },
    {
      q: "WireGuard rekeys roughly every 2 minutes even though the 64-bit nonce counter is nowhere near exhausted. Why?",
      opts: [
        "The counter would overflow within minutes at line rate",
        "ChaCha20 keys weaken with the volume of data they encrypt",
        "NAT mappings expire unless a fresh handshake refreshes them",
        "To bound the forward-secrecy window — a stolen session key exposes at most ~2–3 minutes of traffic",
      ],
      a: 3,
      why: "Frequent rekeying shrinks the blast radius of any single compromised session key to a couple of minutes — **forward secrecy at fine granularity**. 2⁶⁴ messages is centuries at line rate, and NAT bindings are kept alive by data and keepalives, not handshakes.",
    },
    {
      q: "For a WireGuard peer, `AllowedIPs = 0.0.0.0/0` does two distinct jobs. Which pair is it?",
      opts: [
        "Egress routing and ingress filtering: outbound packets to those destinations are sent to that peer, and decrypted packets whose *inner source* isn't in the list are dropped",
        "It selects which peer outbound packets go to — nothing more",
        "It validates inner source addresses on receive — nothing more",
        "It assigns those addresses to the wg interface itself",
      ],
      a: 0,
      why: "AllowedIPs is WireGuard's **cryptokey routing table**, consulted in both directions: destination lookup on send, inner-source check after decrypt. Remembering only one half is the classic gap — the ingress check is why a compromised peer can't spoof traffic 'from' addresses it wasn't assigned.",
    },
    {
      q: "Peer A already owns AllowedIPs 10.0.0.0/24. You configure the same 10.0.0.0/24 on peer B. What does WireGuard do?",
      opts: [
        "Keeps both; packets to that subnet load-balance across A and B",
        "Rejects the configuration with an overlap error",
        "Moves the prefix to B — the cryptokey table maps each IP to exactly one peer, so A silently loses it",
        "A keeps it — the first configuration wins",
      ],
      a: 2,
      why: "The cryptokey routing table has **one owner per prefix**: assigning it to B reassigns it, silently removing it from A — a frequent source of 'adding a peer broke another peer' mysteries. There's no error and no balancing; last write wins.",
    },
    {
      q: "WireGuard over an IPv6 underlay with a 1500-byte path MTU; WireGuard's overhead there is 80 bytes. Correct tunnel MTU?",
      opts: ["1500 — WireGuard fragments internally", "1280", "1440", "1420"],
      a: 3,
      why: "1500 − 80 (40 IPv6 + 8 UDP + 32 WireGuard) = **1420**, which is exactly wg-quick's default — chosen so the tunnel works even on IPv6 underlays. 1440 assumes the 60-byte IPv4 overhead; leaving 1500 means every full-size inner packet exceeds the underlay and WireGuard does not fragment for you.",
    },
    {
      q: "Both peers sit behind symmetric NATs: each NAT allocates a fresh, unpredictable public port per destination. Hole punching keeps failing. What actually works?",
      opts: [
        "Querying several STUN servers until one reveals a stable port",
        "A relay (TURN/DERP-style) — with per-destination random mappings on both sides, neither peer can name a workable target to punch toward",
        "Shorter keepalives to hold the mappings open",
        "Both peers using UPnP to map ports on the carrier NAT",
      ],
      a: 1,
      why: "Punching requires at least one side's mapping to be **predictable from a third-party observation**, and symmetric NATs on both ends destroy that: the STUN-observed port is not the port used toward the peer. More STUN servers just measure the randomness; UPnP doesn't exist on a carrier's NAT — hence the relay fallback every serious stack ships.",
    },
    {
      q: "Peer A is behind a symmetric NAT; peer B is behind a full-cone NAT (endpoint-independent mapping *and* filtering). Can they connect directly?",
      opts: [
        "No — a symmetric NAT on either side always forces a relay",
        "Only if the symmetric NAT supports UPnP",
        "Yes — A sends first to B's known mapping (endpoint-independent filtering admits packets from anyone), and B replies to the source address it observed on A's packet",
        "Yes, but only over TCP",
      ],
      a: 2,
      why: "B's full-cone mapping accepts packets **from any source**, so A's unpredictable symmetric mapping doesn't matter — B simply learns it from the arriving packet and replies there, which A's NAT permits as return traffic. 'Symmetric always means relay' is the overcorrection: it takes symmetric-ish behavior on *both* sides (or strict filtering opposite a symmetric mapper) to force one.",
    },
    {
      q: "A laptop behind NAT holds a WireGuard tunnel to a server with a public IP. Which side needs persistent-keepalive configured, and why?",
      opts: [
        "The laptop — keepalives exist to refresh its own NAT's outbound mapping, and only traffic from the inside can do that",
        "The server — it pings to verify the client is still alive",
        "Both sides, or the binding expires anyway",
        "Neither — the periodic rekey handshake keeps the binding open",
      ],
      a: 0,
      why: "The NAT binding is the **laptop's** state, refreshed only by packets flowing outward through it — the server can't send anything until that mapping exists and stays warm. Rekeys don't help an idle tunnel: WireGuard is silent when there's no data, which is precisely why the option exists.",
    },
    {
      q: "WireGuard uses a plain 64-bit counter as its AEAD nonce. Why is that safe, when random nonces at high volume are dangerous for ChaCha20-Poly1305?",
      opts: [
        "Counters are unpredictable to attackers, unlike random nonces",
        "Each session key is fresh from the handshake and the counter never repeats under it — while random 96-bit nonces start colliding by the birthday bound at large message counts",
        "Random nonces would be equally safe; the counter exists only to drive the replay window",
        "ChaCha20 requires sequential nonces to keep its keystream contiguous",
      ],
      a: 1,
      why: "Nonce safety is about **uniqueness per key**, which a counter under a per-session key guarantees by construction; random nonces only promise it probabilistically, and the birthday bound erodes that at scale. The replay-window answer is half-true — counters do enable it — but 'random is equally safe' is exactly the false premise.",
    },
    {
      q: "You parallelize decryption across a worker pool. Handshakes succeed, but every ~2 minutes you get a burst of authentication failures that then clears up. First suspect?",
      opts: [
        "The replay window rejecting packets your threads finish out of order",
        "Poly1305 tag verification isn't thread-safe",
        "MTU — the larger handshake packets are being fragmented",
        "Workers holding a stale session key across rekeys — keys rotate about every 2 minutes, so key state must be shared or refreshed, and the previous key honored briefly during the transition",
      ],
      a: 3,
      why: "The ~2-minute period is the fingerprint of **rekey timing**: workers that snapshot the session key keep verifying against a dead key until they resync, so packets under the new key fail auth. Correct implementations keep the previous key valid for a grace window; replay-window reordering would cause drops continuously, not on a 2-minute rhythm.",
    },
  ],

  ship: [
    {
      q: "Your iOS packet tunnel works from Xcode, but in the TestFlight build the VPN toggle flips on and immediately off — the provider process never launches. First check?",
      opts: [
        "App Transport Security blocking the provider's server connection",
        "The distribution provisioning profile and entitlements — packet-tunnel requires the Network Extension entitlement on both the app and the extension, and dev-signed profiles don't carry over to distribution builds automatically",
        "TestFlight sandboxes network extensions; it can only work in the App Store build",
        "The 'background modes' capability is missing",
      ],
      a: 1,
      why: "A provider that never launches under distribution signing is the signature of **entitlement/profile mismatch** — the NE entitlement must be present in *both* targets' distribution profiles. ATS governs URL loading inside apps, not extension launch, and TestFlight runs extensions exactly like the App Store does.",
    },
    {
      q: "A user disconnects your VPN from inside your app, but iOS keeps re-establishing the tunnel seconds later. Why?",
      opts: [
        "The server keeps pushing reconnects; block it in the firewall",
        "stopTunnel is asynchronous and your completion handler never fires",
        "iOS restarts crashed providers automatically regardless of user intent",
        "On-demand rules — the OS re-starts the tunnel whenever matching traffic appears, until you clear isOnDemandEnabled rather than just stopping the session",
      ],
      a: 3,
      why: "With **on-demand** enabled, stopping the session treats the very next packet as a reason to reconnect — 'user pause' must disable `isOnDemandEnabled` (and save the preferences) first. Nothing here involves the server; on-demand is purely an OS-side policy engine.",
    },
    {
      q: "Users report the iOS tunnel is 'down' every time the phone sits locked for a while, then recovers on unlock. What's actually happening?",
      opts: [
        "Expected platform behavior — iOS suspends the provider during sleep (your sleep() callback fires; timers and keepalives stop), so the right design is to re-handshake on wake rather than fight it",
        "A memory leak is getting the provider killed at lock time",
        "The server's handshake timeout is too aggressive",
        "Data Protection closes your sockets when the device locks",
      ],
      a: 0,
      why: "NEProvider exposes `sleep()`/`wake()` precisely because the system **suspends the extension** to save power — your keepalives and rekey timers simply don't run while asleep. Memory-pressure kills are real on iOS but they're throughput-correlated, not lock-correlated; the lock-time pattern is the tell.",
    },
    {
      q: "Your Windows kill switch blocks all traffic by default — including, accidentally, your own VPN client. Which WFP concept exempts your process's traffic robustly?",
      opts: [
        "Bind your sockets to loopback, which WFP exempts",
        "Run the client as SYSTEM — WFP doesn't filter privileged processes",
        "A higher-weight permit filter keyed to your binary via FWPM_CONDITION_ALE_APP_ID",
        "A permit rule for the VPN server's IP and port",
      ],
      a: 2,
      why: "WFP can match on the **application identity (ALE app ID)**, so a high-weight permit for your signed binary survives server IP changes and can't be borrowed by other software. The IP/port permit is the tempting shortcut — it breaks on failover and lets *any* local app talk to that endpoint through your 'kill switch'.",
    },
    {
      q: "Your wintun read loop pegs a CPU core at 100% even when the tunnel is idle. What's missing?",
      opts: [
        "A smaller ring capacity so reads return sooner",
        "A Sleep(1) between empty reads",
        "Reads via raw IOCTLs like the legacy TAP driver used",
        "Blocking on the session's read-wait event (WaitForSingleObject) until the ring actually has packets",
      ],
      a: 3,
      why: "wintun's shared-memory ring is polled, so an idle loop spins unless you **wait on the driver's read event** and wake only when packets arrive. `Sleep(1)` is the classic bodge — it trades the spin for up to a millisecond of added latency per packet and still burns wakeups.",
    },
    {
      q: "wg-quick points the default route at wg0 — yet WireGuard's own encrypted UDP packets don't loop back into the tunnel. What's the mechanism on Linux?",
      opts: [
        "It marks its own encrypted packets with a fwmark, and an ip rule steers marked traffic to the physical routing table, sidestepping the wg0 default route",
        "It adds a /32 route to the server via the physical interface",
        "The kernel automatically refuses to route a socket's packets into the interface that socket serves",
        "It sends handshakes from a second, unrouted socket",
      ],
      a: 0,
      why: "WireGuard sockets carry a **fwmark**, and wg-quick installs policy rules so marked traffic consults the physical table — routing loops die by classification, not by exceptions. The /32 host route is the other classic technique (and what simpler clients do), but it's brittle on endpoint failover and it isn't what wg-quick installs; the kernel has no automatic anti-loop rule.",
    },
    {
      q: "Your Linux split tunnel uses policy routing. Outbound flows work, but replies your host sends to connections arriving from the LAN silently vanish. Which sysctl is the classic suspect?",
      opts: [
        "net.ipv4.ip_forward is disabled",
        "conntrack table overflow",
        "Strict reverse-path filtering (rp_filter=1) dropping packets whose return route doesn't match their arrival interface — set loose mode (2) or per-interface exceptions",
        "TCP timestamp mismatch across the asymmetric path",
      ],
      a: 2,
      why: "Policy routing creates deliberate asymmetry, and **strict rp_filter** drops any packet that would be answered out a different interface than it arrived on — the canonical split-tunnel footgun. `ip_forward` governs *forwarding through* the box; these are locally terminated connections, so it's not in the path.",
    },
    {
      q: 'Your Android VpnService.Builder calls both addAllowedApplication("com.corp.mail") and addDisallowedApplication("com.game"). What happens?',
      opts: [
        "The allow list wins and the disallow list is ignored",
        "It throws — a VPN's per-app config is either an allow list or a disallow list, never both",
        "The lists merge: allowed minus disallowed",
        "Both are applied per-UID at connect time",
      ],
      a: 1,
      why: "Android forces you to pick a model: **allow list (only these apps tunnel) or disallow list (everyone but these)** — mixing them throws at build time. There's no merge semantics to reason about; your split-tunnel UI has to commit to one paradigm per session.",
    },
    {
      q: "On Android you set tunnel DNS with builder.addDnsServer(), yet some apps still resolve via a hardcoded 8.8.8.8. Can you force them through your resolver?",
      opts: [
        "Yes — addDnsServer makes Android rewrite all port-53 traffic to it",
        "No — hardcoded resolvers always bypass VPNs",
        "Mostly — block UDP 53 and apps fall back to system DNS",
        "Yes — route 8.8.8.8 into the tunnel and intercept/redirect port 53 inside it; addDnsServer only sets the system default and doesn't touch apps that dial resolvers directly",
      ],
      a: 3,
      why: "`addDnsServer` configures the *default* resolver — an app that opens its own socket to 8.8.8.8:53 is just traffic, and if your routes cover it you can **redirect it to your resolver inside the tunnel**. Blocking port 53 is the half-fix that breaks such apps instead of capturing them, since many never fall back.",
    },
    {
      q: 'Your PAC file returns "PROXY p1.corp:8080; DIRECT". p1 is up but answers 502 for one backend host. What does the browser do?',
      opts: [
        "Shows the 502 — failover to DIRECT happens only when the proxy is unreachable (connect failure or timeout), not when it returns an error response",
        "Retries the request via DIRECT automatically",
        "Re-evaluates the PAC and pins DIRECT for that host from then on",
        "Marks p1 dead for all hosts and goes DIRECT globally",
      ],
      a: 0,
      why: "The PAC fallback list is about **connectivity to the proxy**, not the quality of its answers: a 502 is a successful proxy conversation, so it's final. Assuming errors trigger failover is how people ship PACs that 'have a fallback' which never engages when the proxy misbehaves.",
    },
    {
      q: "Product wants 'only Slack goes through the tunnel' on desktop. Destination-IP routing can't express that. What mechanism can?",
      opts: [
        "Maintain /32 routes for every IP Slack connects to",
        "Attribute traffic to its owning process and steer at that layer — WFP app-ID filters on Windows, cgroup/fwmark policy routing on Linux, per-app VPN APIs on mobile",
        "A PAC file returning the tunnel proxy only for Slack's domains",
        "DNS-based routing: resolve Slack's domains into tunnel addresses",
      ],
      a: 1,
      why: "'Which app' is a property of the **process, not the packet**, so you need OS facilities that tag traffic by originator — app-ID filtering, cgroup marks, per-app VPN. The /32 approach is the tempting hack that dies on CDNs: Slack's IP set is huge, shared with other services, and changes hourly.",
    },
    {
      q: "Your macOS client implements reconnect logic in the GUI app; users report the VPN dies whenever they quit the app. The architectural fix?",
      opts: [
        "Keep it in the GUI but add a login item so the app relaunches",
        "Move reconnect logic to the server side",
        "Move the engine — tunnel lifecycle and the reconnect state machine — into the daemon/system extension, and make the GUI a thin IPC client that can quit freely",
        "Prevent app termination while the VPN is up",
      ],
      a: 2,
      why: "The tunnel's owner must have the tunnel's lifetime, which means the **privileged, always-running component** — the GUI should only observe and command over IPC. Auto-relaunch hacks still leave gaps at logout, crashes, and Fast User Switching; connection-broker logic can't live on the server because the client is the side that must dial.",
    },
    {
      q: "A crash reproduces only on Windows ARM64 in release builds. Which engineering practice catches this class of bug before users do?",
      opts: [
        "A CI matrix that builds and runs the test suite on every shipped target triple — including release profile — so platform- and optimization-specific breakage surfaces pre-release",
        "More unit tests — coverage is coverage regardless of where it runs",
        "Fuzzing the packet parsers under ASan on the dev machine",
        "Relying on the beta channel; some bugs are only findable in the field",
      ],
      a: 0,
      why: "Bugs keyed to *target × profile* are invisible anywhere except that cell of the **build matrix** — tests on your x86 dev box can't observe ARM64 release codegen no matter how many you write. Fuzzing finds input-dependent bugs, not platform-dependent ones; betas catch what CI could have, just with users as the sensor.",
    },
    {
      q: "At a hotel, your VPN client with a strict kill switch connects to Wi-Fi but the user can never get online. Why do production clients ship captive-portal handling?",
      opts: [
        "Hotels block VPN protocols, so the client must switch to TCP 443",
        "The portal needs the device's real MAC address, which the tunnel hides",
        "DNS through the tunnel resolves the portal's domain incorrectly",
        "Pre-authentication, the network only permits plaintext access to the portal — a strict tunnel/kill switch blocks that redirect flow, so the client must detect the portal and temporarily allow direct access to complete sign-in",
      ],
      a: 3,
      why: "A captive network is a **walled garden until you authenticate**: the tunnel can't come up (its packets are blocked), and the kill switch then blocks the portal traffic that would fix it — a deadlock only portal detection plus a scoped bypass breaks. Protocol blocking is real at some venues, but it doesn't explain the universal pre-auth failure pattern.",
    },
    {
      q: "Your VPN daemon exposes a localhost control socket, and it turns out any local process can command 'disconnect'. The correct hardening?",
      opts: [
        "Nothing needed — binding to 127.0.0.1 already restricts it to trusted code",
        "Use a high random port number as a shared secret",
        "Authenticate the peer with OS facilities — SO_PEERCRED/UID checks on Unix sockets, code-signing/audit-token verification on XPC — before honoring any command",
        "Wrap the loopback connection in TLS",
      ],
      a: 2,
      why: "Localhost is a *place*, not an identity: every process on the machine — including malware running as the user — can reach 127.0.0.1, so you must **verify who is calling** using peer credentials or code-signature checks. TLS on loopback encrypts a channel you didn't need encrypted while still accepting any client that connects.",
    },
    {
      q: "Your self-updater stops the daemon, swaps binaries, and restarts. QA finds traffic leaks during the gap. What actually guarantees leak-free updates?",
      opts: [
        "Only updating at boot, before networking starts",
        "Enforcing the kill switch with rules that outlive the process — WFP persistent/boot-time filters or equivalent kernel firewall state — so the block holds while no daemon is running",
        "Handing the open TUN fd to the new daemon so the tunnel never drops",
        "Showing a 'do not browse' notice during the update",
      ],
      a: 1,
      why: "Only **kernel-resident policy** covers the window when your code isn't running — persistent WFP filters (or nftables rules) keep blocking through the restart, and even through a crash-loop. The fd-handoff trick minimizes downtime but guarantees nothing if the new daemon fails to start; the leak protection must not share fate with the process being replaced.",
    },
  ],
};
